- hosts: unicorn
  become: true
  tasks:
    - name: Create new user
      user:
        name: workshop
    - name: Install unzip
      apt:
        name:
          unzip
    - name: Create tmp folder
      file:
        path: '/home/workshop/hello/'
        state: directory
        owner: workshop
        group: workshop
        mode: '0755'
    - name: Download file
      get_url:
        url: https://github.com/trietphm/workshop-rails-vue/releases/download/v0.1/hello-world.zip
        dest: /tmp/hello-world.zip
    - name: Extract file into hello
      become: true
      unarchive:
        src: /tmp/hello-world.zip
        remote_src: yes
        dest: '/home/workshop/hello'
    - name: Execute binary file
      command: './hello-world'
      args:
        chdir: '/home/workshop/hello'
      register: hello_world_message
    - name: Execute binary file again
      command: './hello-world'
      args:
        chdir: '/home/workshop/hello'
      register: cow_message
      environment:
        COW: 'true'
        MESSAGE: 'Hello guys!'
    - name: Write the two above variables values into output file
      become: true
      copy:
        content: "{{hello_world_message.stdout}}\n {{cow_message.stdout}}"
        dest: /home/workshop/hello/messages.txt
